### ISSUE TITLE
Separate layers

### ISSUE THREAD

**Issue by matrixik** [go-bootstrap/go-bootstrap#23]
Hi,

I don't know if it reasonable for such project generator but maybe at some point it would be possible to generate projects that have separate layers for frontend and database.

Go web app example from sourcegraph: https://github.com/sourcegraph/thesrc
More info why it can be useful: https://github.com/sourcegraph/thesrc/issues/1

Best regards

**Comment by didip** [comment]
When you say separate layers, what kind of layers are you thinking about? 2 services talking to each other?

**Comment by matrixik** [comment]
Yes, why it can be useful: https://github.com/sourcegraph/thesrc/issues/1

P.S. Other example https://github.com/dorajistyle/goyangi

**Comment by didip** [comment]
I like the general trends of SOA, I even thought of providing API scaffolding for this project.
But API stories are diverse, each company/individual do their own thing and all of them have little in common. I'll give you a few examples:

* **Authentication:** OAuth1a vs OAuth2 vs HTTP Auth vs Signed HMAC. Which one to choose?
* **Payload:** JSON is an easy choice, but there will be other users demanding Protocol Buffer or Thrift.
* **RPC:** Eventually, every simple service will grow an RPC endpoint or two. gRPC seems to be the library to choose.
* **Duplex Connections:** Request -> Response model is not going to be enough for some users, especially since real-time web is all the rage nowadays. Which one to choose: Raw TCP vs Websocket vs Server Side Events?

This list of requirements makes me think that API should be handled by a different project.

**Comment by matrixik** [comment]
Thank you for comment and I understood your concerns.
