### ISSUE TITLE
"/" route default to a generic index.html.tmpl

### ISSUE THREAD

**Issue by albertchan** [go-bootstrap/go-bootstrap#26]
This is not an issue per se, but I was wondering if it's possible to have the "/" route default to a generic `index.html.tmpl` instead of redirecting to "/login" if a user session doesn't exists? Thanks.

**Comment by Knorkebrot** [comment]
Since this is just a bootstrapper you'll have to touch the code anyway. Removing the need to login is easy, just remove the [MustLogin middleware][1] for '/' and change the [GetHome Handler][2] to be independent of a user.

[1]: https://github.com/go-bootstrap/go-bootstrap/blob/70226ba028d15c92f00753b2deff854e854dd20d/blank/main.go#L72
[2]: https://github.com/go-bootstrap/go-bootstrap/blob/70226ba028d15c92f00753b2deff854e854dd20d/blank/handlers/home.go

**Comment by didip** [comment]
@albertchan Yeah, I have to agree with @Knorkebrot, it's fairly trivial to mold the generated app to be what you want, but I will explain the decision why it is the way it is.

1. Based on what I've seen so far, when a startup grows, it's natural for the marketing page to be separated from the actual web app.

2. When building microservices, landing page is often unnecessary. go-bootstrap is initially conceived because building many small services in Go is tedious.
